# your domain
domain: proxy.moneyfly.club

# database url
database_url: ""

# cloudflare api
cf_email: ""
cf_key: ""

# source definition file
source-files:
  # use local file
  - ./config/source.yaml
  # use web file
  - http://proxy.moneyfly.club/source.yaml
