# 模糊抓取订阅链接
- type: webfuzzsub
  options:
    url: https://raw.githubusercontent.com/du5/free/master/sub.list
- type: webfuzzsub
  options:
    url: https://uploader.shimo.im/f/KO9YB4sh4a9OSwXw.txt?attname=1.txt
- type: webfuzzsub
  options:
    url: https://t.me/s/ssrv2taytgshare?before=743

# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/v2ray
- type: subscribe
  options:
    url: http://129.211.76.192/ssr/0904ssr.txt
- type: subscribe
  options:
    url: https://proxy.tgbot.co/ss/sub
- type: subscribe
  options:
    url: https://proxy.tgbot.co/vmess/sub

# 网页模糊抓取
- type: webfuzz
  options:
    url: https://merlinblog.xyz/wiki/freess.html
- type: webfuzz
  options:
    url: https://bihai-v2ray.netlify.com
- type: webfuzz
  options:
    url: https://ss.pythonic.life/
- type: webfuzz
  options:
    url: https://www.youneed.win/free-ss
- type: webfuzz
  options:
    url: https://www.youneed.win/free-ssr
- type: webfuzz
  options:
    url: https://raw.githubusercontent.com/freefq/free/master/README.md
- type: webfuzz
  options:
    url: https://zfjvpn.gitbook.io/
- type: webfuzz
  options:
    url: https://fanqiang.network/free-v2ray
- type: webfuzz
  options:
    url: https://www.freefq.com/d/file/free-ssr/20200811/1f3e9d0d0064f662457062712dcf1b66.txt
- type: webfuzz
  options:
    url: https://merlinblog.xyz/wiki/freess.html
- type: webfuzz
  options:
    url: https://zfjvpn.gitbook.io/123/
- type: webfuzz
  options:
    url: https://raw.githubusercontent.com/ruanfei/ShadowsocksRRShare/master/ss/ss.txt
- type: webfuzz
  options:
    url: https://raw.githubusercontent.com/ruanfei/ShadowsocksRRShare/master/ssr/ssr.txt
- type: webfuzz
  options:
    url: https://raw.githubusercontent.com/pojiezhiyuanjun/freev2/master/all.txt
- type: webfuzz
  options:
    url: https://raw.githubusercontent.com/zu1k/ssrtool-crawler/master/data/ssr.txt
- type: webfuzz
  options:
    url: https://raw.githubusercontent.com/freefq/free/master/README.md
- type: webfuzz
  options:
    url: https://raw.githubusercontent.com/52bp/52bp.github.io/master/freesite.html

# tg频道抓取
- type: tgchannel
  options:
    channel: ssrList
    num: 200
- type: tgchannel
  options:
    channel: SSRSUB
    num: 200
- type: tgchannel
  options:
    channel: FreeSSRNode
    num: 200
- type: tgchannel
  options:
    channel: V2List
    num: 200
- type: tgchannel
  options:
    channel: ssrtool
    num: 200
- type: tgchannel
  options:
    channel: mianfeifenxiang
    num: 200
- type: tgchannel
  options:
    channel: freeshadowsock
    num: 200
- type: tgchannel
  options:
    channel: jiedianfenxiang
    num: 200
- type: tgchannel
  options:
    channel: fanqiang666
    num: 200
- type: tgchannel
  options:
    channel: FreeSSR666
    num: 200
- type: tgchannel
  options:
    channel: vmessr
    num: 200
- type: tgchannel
  options:
    channel: ssrtool_crack
    num: 200
- type: tgchannel
  options:
    channel: Shadowsocks_R
    num: 200
- type: tgchannel
  options:
    channel: dangzhibu
    num: 200
- type: tgchannel
  options:
    channel: ssrshares
    num: 200
- type: tgchannel
  options:
    channel: gongyijichangfenxiang
    num: 200
- type: tgchannel
  options:
    channel: ioshkj007
    num: 200
- type: tgchannel
  options:
    channel: fanqiang666
    num: 200
- type: tgchannel
  options:
    channel: FreeSSR666
    num: 200
- type: tgchannel
  options:
    channel: vmessr
    num: 200
- type: tgchannel
  options:
    channel: ssrtool_crack
    num: 200
- type: tgchannel
  options:
    channel: Shadowsocks_R
    num: 200
- type: tgchannel
  options:
    channel: moneyfly01
    num: 200
- type: tgchannel
  options:
    channel: ssrv2taytgshare
    num: 200
- type: tgchannel
  options:
    channel: freeshadowsock
    num: 200
- type: tgchannel
  options:
    channel: gyjclub
    num: 200
- type: tgchannel
  options:
    channel: vpnchina
    num: 200
- type: tgchannel
  options:
    channel: XRAcc
    num: 200
- type: tgchannel
  options:
    channel: TelMTProto
    num: 200
- type: tgchannel
  options:
    channel: apkdl_bot
    num: 200
- type: tgchannel
  options:
    channel: TgProxies
    num: 200
- type: tgchannel
  options:
    channel: zonghe_info
    num: 200
- type: tgchannel
  options:
    channel: youmtp
    num: 200
- type: tgchannel
  options:
    channel: yo520
    num: 200

# 翻墙党论坛抓取
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum-48-1.html

# 某个网站抓取
- type: web-freessrxyz
  options:
